apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    events {
      worker_connections  10240;
    }
    http {
      server {
          listen       80;
          location / {
             proxy_pass http://course-app:3000;
          }
      }
    }
